Updating action

diff --git a/.github/workflows/test-example-site.yml b/.github/workflows/test-example-site.yml
--- a/.github/workflows/test-example-site.yml
+++ b/.github/workflows/test-example-site.yml
@@ -73,7 +73,8 @@ jobs:
           ls -la
           echo "Test results directory:"
           ls -la test-results || echo "test-results not found"
-
+          echo "Playwright report directory:"
+          ls -la playwright-report || echo "playwright-report not found"
       - name: Get the failure count
         id: tests
         run: |
